# Generated by Django 6.0.1 on 2026-01-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ATHLETE'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='athlete',
            field=models.ForeignKey(limit_choices_to={'role': 'ATHLETE'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='academy.batch'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academy.batch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.schedule'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academy.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('batch', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule', 'athlete')},
        ),
    ]
