# Generated by Django 6.0.1 on 2026-03-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_feestructure_fee_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academy.batch'),
        ),
    ]
