# Generated by Django 6.0.1 on 2026-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_announcement_created_by_announcement_target_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
