# Generated by Django 6.0.1 on 2026-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
