# Generated by Django 6.0.1 on 2026-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_athleteprofile_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
