# Generated by Django 6.0.1 on 2026-03-15 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_announcement_created_by_announcement_target_audience_and_more'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='weight_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Weight of this metric in overall performance index (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_index', models.DecimalField(decimal_places=2, default=0.0, help_text='Weighted overall performance score (0-100)', max_digits=6)),
                ('rank_in_batch', models.IntegerField(blank=True, help_text="Athlete's rank within their batch for this sport", null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'ATHLETE'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='academy.sport')),
            ],
            options={
                'ordering': ['-performance_index'],
                'unique_together': {('athlete', 'sport')},
            },
        ),
    ]
