# Generated by Django 6.0.1 on 2026-03-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_announcement_created_by_announcement_target_audience_and_more'),
        ('performance', '0002_performancemetric_weight_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetric',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='academy.sport'),
        ),
    ]
