# Generated by Django 6.0.1 on 2026-03-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_performancemetric_sport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
    ]
