# Generated by Django 6.0.1 on 2026-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_alter_testresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
