# Generated by Django 6.0.1 on 2026-03-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='verification_token',
        ),
    ]
